# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stories
email: makertolentino@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Audio documentaries of the life and times of hip-hop artist, Son of Ran
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://randytolentino.com" # the base hostname & protocol for your site
twitter_username: techtolentino
github_username:  techtolentino

# Build settings
markdown: kramdown
